<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<div class="min-h-screen bg-gray-50">

    <main class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div class="bg-white rounded-lg shadow p-6">
            <h2 class="text-2xl font-semibold mb-4">Token Bağlantısı</h2>
            <p class="text-gray-600">
                Lütfen e-postanızı kontrol edin, tek seferlik token'ınız (ott) gönderildi!
            </p>
        </div>
    </main>
</div>
</body>
</html>